# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class wzkit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(291, 143)
        self.running = QtWidgets.QPushButton(Dialog)
        self.running.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.running.setObjectName("running")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 20, 117, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_dir = QtWidgets.QToolButton(self.widget)
        self.file_dir.setObjectName("file_dir")
        self.horizontalLayout.addWidget(self.file_dir)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(40, 50, 201, 51))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtWidgets.QFormLayout(self.widget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.now_wz = QtWidgets.QTextEdit(self.widget1)
        self.now_wz.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.now_wz.setObjectName("now_wz")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.now_wz)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.to_wz = QtWidgets.QTextEdit(self.widget1)
        self.to_wz.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.to_wz.setObjectName("to_wz")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.to_wz)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Juse帮您批量替换尾缀"))
        self.running.setText(_translate("Dialog", "Start!"))
        self.file_dir.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "未选择文件夹"))
        self.label_2.setText(_translate("Dialog", "现尾缀："))
        self.label_3.setText(_translate("Dialog", "目标尾缀："))


